### GET request to example server
GET http://localhost:1337/api/message


###
POST http://localhost:1337
Content-Type: application/json

{
  "name": "test",
  "location": "123 friend park ave"
}
###
GET http://localhost:1337/setup
###
GET http://localhost:1337/read

